apiVersion: apps/v1
kind: Deployment

metadata:
  name: simple-fe
  labels:
    app: simple-fe

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      app: simple-fe

  template:
    metadata:
      labels:
        app: simple-fe

    spec:
      containers:
        - name: simple-fe
          image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}

          ports:
            - containerPort: 80

          env:
            - name: NODE_ENV
              value: "production"

          