apiVersion: apps/v1
kind: Deployment

metadata:
  name: simple-be
  labels:
    app: simple-be

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: simple-be

  template:
    metadata:
      labels:
        app: simple-be

    spec:
      containers:
        - name: simple-be
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}

          ports:
            - containerPort: 3000

          env:
            - name: NODE_ENV
              value: "production"

          