frontend:
  replicaCount: 2

  image:
    repository: jbabajohn/simple-fe
    tag: v2

  service:
    port: 80


backend:
  replicaCount: 2

  image:
    repository: jbabajohn/simple-be
    tag: v2

  service:
    port: 3000